services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./storage:/storage

  inference:
    build:
      context: ./inference
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
      - ./outputs:/app/outputs